### ISSUE TITLE
Work links in mobile

### ISSUE THREAD

**Issue by charlydsgn** [808loud/charlie-portfolio#56] opened 2016-06-24 21:36 UTC
All the work link buttons do not load the modal window when tapped on my mobile device.

**Comment by 808loud** [comment] 2016-06-24 22:31
Cannot reproduce this. 

Can you do the following: 
- Clear your cache
- Refresh and retest
- If you're still seeing the issue, can you provide me with the device and browser version?

**Comment by 808loud** [comment] 2016-06-25 00:35
Closing this unless I hear otherwise

**Closed as completed by 808loud** 2016-06-25 00:35 UTC
