### ISSUE TITLE
Heading line height

### ISSUE THREAD

**Issue by charlydsgn** [808loud/charlie-portfolio#50] opened 2016-06-23 21:16 UTC
For consistency can you make the line spacing for "Consultant for hire" the same as "Your place or mine?"
<img width="366" alt="screen shot 2016-06-23 at 4 20 35 pm" src="https://cloud.githubusercontent.com/assets/20047847/16320499/bd48b296-395d-11e6-9080-b56d5a5574f9.png">
<img width="403" alt="screen shot 2016-06-23 at 4 21 59 pm" src="https://cloud.githubusercontent.com/assets/20047847/16320505/c61a605e-395d-11e6-8009-79a7e1b97f0c.png">

**Comment by 808loud** [comment] 2016-06-23 21:44
Related to #48

**Comment by 808loud** [comment] 2016-06-23 22:53
Duplicate of #48

**Comment by 808loud** [comment] 2016-06-24 17:18
Solved with https://github.com/808loud/charlie-portfolio/commit/ced4320a09347c6457a606928d7696b4fcc55b9b

**Closed as completed by 808loud** 2016-06-24 17:18 UTC
