### ISSUE TITLE
 Mobile break point, modal heading line height

### ISSUE THREAD

**Issue by charlydsgn** [808loud/charlie-portfolio#48] opened 2016-06-23 18:51 UTC
Does not break properly in Firefox, it did at one point. See below. 
<img width="335" alt="screen shot 2016-06-23 at 1 56 44 pm" src="https://cloud.githubusercontent.com/assets/20047847/16315857/90d07b72-3949-11e6-8ab7-f8ed378c9029.png">

**Comment by 808loud** [comment] 2016-06-23 19:12
Is that a screenshot of your full browser window?

**Comment by charlydsgn** [comment] 2016-06-23 21:05
It breaks properly now. The exception is the X, still not centered in any break point. Also, can you increase the line spacing of the header text "uber finder + product description page" and apply this to all instances? Use your best judgement. See below. 
<img width="334" alt="screen shot 2016-06-23 at 4 07 05 pm" src="https://cloud.githubusercontent.com/assets/20047847/16320142/eef822ce-395b-11e6-8eac-750265f64f24.png">
<img width="322" alt="screen shot 2016-06-23 at 4 10 42 pm" src="https://cloud.githubusercontent.com/assets/20047847/16320221/53c60464-395c-11e6-849f-cdd46dfb449e.png">
<img width="334" alt="screen shot 2016-06-23 at 4 07 05 pm" src="https://cloud.githubusercontent.com/assets/20047847/16320222/53c5f050-395c-11e6-973b-8d0c210d76f0.png">

**Comment by 808loud** [comment] 2016-06-23 22:53
Duplicate of #48

**Comment by 808loud** [comment] 2016-06-23 23:19
Sorry for all the notifications, but I wanted to document my actions properly. Closing this in favor of #50

**Closed as completed by 808loud** 2016-06-23 23:19 UTC

**Comment by charlydsgn** [comment] 2016-06-23 23:40
No problem, I don't mind.
